#include "CueSheetExportService.h"

#include <spdlog/spdlog.h>

#include <cmath>
#include <fstream>
#include <regex>
#include <sstream>

namespace BeatMate::Services::Export {

bool CueSheetExportService::exportCueSheet(const std::string& outputPath,
                                             const CueSheetMetadata& metadata,
                                             const std::vector<CueIndex>& indices) {
    std::string content = generateCueContent(metadata, indices);

    std::ofstream ofs(outputPath);
    if (!ofs.is_open()) {
        spdlog::error("CueSheetExportService: Failed to open file: {}", outputPath);
        return false;
    }

    ofs << content;
    spdlog::info("CueSheetExportService: Exported CUE sheet with {} tracks to {}",
                 indices.size(), outputPath);
    return true;
}

bool CueSheetExportService::exportFromTracks(const std::string& outputPath,
                                               const std::string& audioFileName,
                                               const std::vector<Models::Track>& tracks,
                                               const std::vector<double>& startTimesSeconds) {
    if (tracks.size() != startTimesSeconds.size()) {
        spdlog::error("CueSheetExportService: Tracks/times count mismatch");
        return false;
    }

    CueSheetMetadata metadata;
    metadata.fileName = audioFileName;
    metadata.fileType = "WAVE";

    std::vector<CueIndex> indices;
    for (size_t i = 0; i < tracks.size(); ++i) {
        auto idx = timeToIndex(static_cast<int>(i + 1), startTimesSeconds[i],
                                tracks[i].title, tracks[i].artist);
        indices.push_back(idx);
    }

    return exportCueSheet(outputPath, metadata, indices);
}

bool CueSheetExportService::exportFromMixSession(const std::string& outputPath,
                                                    const std::string& audioFileName,
                                                    const std::string& djName,
                                                    const std::string& mixTitle,
                                                    const std::vector<Models::Track>& tracks,
                                                    const std::vector<double>& transitionTimesSeconds) {
    CueSheetMetadata metadata;
    metadata.title = mixTitle;
    metadata.performer = djName;
    metadata.fileName = audioFileName;
    metadata.fileType = "WAVE";
    metadata.comment = "Generated by BeatMate";

    std::vector<CueIndex> indices;
    for (size_t i = 0; i < tracks.size(); ++i) {
        double startTime = (i < transitionTimesSeconds.size()) ? transitionTimesSeconds[i] : 0.0;
        auto idx = timeToIndex(static_cast<int>(i + 1), startTime,
                                tracks[i].title, tracks[i].artist);
        indices.push_back(idx);
    }

    return exportCueSheet(outputPath, metadata, indices);
}

bool CueSheetExportService::parseCueSheet(const std::string& filePath,
                                            CueSheetMetadata& outMetadata,
                                            std::vector<CueIndex>& outIndices) {
    std::ifstream ifs(filePath);
    if (!ifs.is_open()) return false;

    outIndices.clear();
    CueIndex currentIndex;
    bool inTrack = false;
    std::string line;

    while (std::getline(ifs, line)) {
        size_t start = line.find_first_not_of(" \t");
        if (start == std::string::npos) continue;
        line = line.substr(start);

        if (line.substr(0, 4) == "REM ") {
            std::string rem = line.substr(4);
            if (rem.substr(0, 6) == "GENRE ") outMetadata.genre = rem.substr(6);
            else if (rem.substr(0, 5) == "DATE ") outMetadata.date = rem.substr(5);
            else if (rem.substr(0, 8) == "COMMENT ") outMetadata.comment = rem.substr(8);
        }
        else if (line.substr(0, 6) == "TITLE ") {
            std::string val = line.substr(6);
            if (val.front() == '"' && val.back() == '"')
                val = val.substr(1, val.size() - 2);
            if (!inTrack) outMetadata.title = val;
            else currentIndex.title = val;
        }
        else if (line.substr(0, 10) == "PERFORMER ") {
            std::string val = line.substr(10);
            if (val.front() == '"' && val.back() == '"')
                val = val.substr(1, val.size() - 2);
            if (!inTrack) outMetadata.performer = val;
            else currentIndex.performer = val;
        }
        else if (line.substr(0, 5) == "FILE ") {
            std::regex re("FILE\\s+\"([^\"]+)\"\\s+(\\w+)");
            std::smatch match;
            if (std::regex_search(line, match, re)) {
                outMetadata.fileName = match[1].str();
                outMetadata.fileType = match[2].str();
            }
        }
        else if (line.substr(0, 6) == "TRACK ") {
            if (inTrack) outIndices.push_back(currentIndex);
            currentIndex = CueIndex{};
            std::regex re("TRACK\\s+(\\d+)\\s+AUDIO");
            std::smatch match;
            if (std::regex_search(line, match, re)) {
                currentIndex.trackNumber = std::stoi(match[1].str());
            }
            inTrack = true;
        }
        else if (line.substr(0, 8) == "INDEX 01") {
            std::regex re("INDEX\\s+01\\s+(\\d+):(\\d+):(\\d+)");
            std::smatch match;
            if (std::regex_search(line, match, re)) {
                currentIndex.minutes = std::stoi(match[1].str());
                currentIndex.seconds = std::stoi(match[2].str());
                currentIndex.frames = std::stoi(match[3].str());
            }
        }
        else if (line.substr(0, 5) == "ISRC ") {
            currentIndex.isrc = line.substr(5);
        }
    }

    if (inTrack) outIndices.push_back(currentIndex);

    spdlog::info("CueSheetExportService: Parsed {} tracks from {}", outIndices.size(), filePath);
    return !outIndices.empty();
}

CueIndex CueSheetExportService::timeToIndex(int trackNumber, double seconds,
                                              const std::string& title,
                                              const std::string& performer) {
    CueIndex idx;
    idx.trackNumber = trackNumber;
    idx.title = title;
    idx.performer = performer;
    idx.minutes = static_cast<int>(seconds) / 60;
    idx.seconds = static_cast<int>(seconds) % 60;
    idx.frames = static_cast<int>((seconds - std::floor(seconds)) * 75.0);
    return idx;
}

double CueSheetExportService::indexToSeconds(const CueIndex& index) {
    return index.minutes * 60.0 + index.seconds + index.frames / 75.0;
}

std::string CueSheetExportService::formatTime(int minutes, int seconds, int frames) {
    char buf[16];
    std::snprintf(buf, sizeof(buf), "%02d:%02d:%02d", minutes, seconds, frames);
    return buf;
}

std::string CueSheetExportService::escapeString(const std::string& s) const {
    return "\"" + s + "\"";
}

std::string CueSheetExportService::generateCueContent(const CueSheetMetadata& metadata,
                                                         const std::vector<CueIndex>& indices) const {
    std::ostringstream oss;

    if (!metadata.genre.empty()) oss << "REM GENRE " << metadata.genre << "\n";
    if (!metadata.date.empty()) oss << "REM DATE " << metadata.date << "\n";
    if (!metadata.comment.empty()) oss << "REM COMMENT " << escapeString(metadata.comment) << "\n";
    if (!metadata.discId.empty()) oss << "REM DISCID " << metadata.discId << "\n";
    if (!metadata.performer.empty()) oss << "PERFORMER " << escapeString(metadata.performer) << "\n";
    if (!metadata.title.empty()) oss << "TITLE " << escapeString(metadata.title) << "\n";
    if (!metadata.catalog.empty()) oss << "CATALOG " << metadata.catalog << "\n";

    std::string fname = metadata.fileName.empty() ? "output.wav" : metadata.fileName;
    std::string ftype = metadata.fileType.empty() ? "WAVE" : metadata.fileType;
    oss << "FILE " << escapeString(fname) << " " << ftype << "\n";

    for (const auto& idx : indices) {
        oss << "  TRACK " << (idx.trackNumber < 10 ? "0" : "") << idx.trackNumber << " AUDIO\n";
        if (!idx.title.empty()) oss << "    TITLE " << escapeString(idx.title) << "\n";
        if (!idx.performer.empty()) oss << "    PERFORMER " << escapeString(idx.performer) << "\n";
        if (!idx.isrc.empty()) oss << "    ISRC " << idx.isrc << "\n";
        if (!idx.songwriter.empty()) oss << "    SONGWRITER " << escapeString(idx.songwriter) << "\n";
        oss << "    INDEX 01 " << formatTime(idx.minutes, idx.seconds, idx.frames) << "\n";
    }

    return oss.str();
}

}
