#pragma once
#include <string>
#include <vector>
#include "../../models/Track.h"
#include "../../models/Playlist.h"

namespace BeatMate::Services::Export {

struct PdfPageOptions {
    double pageWidth = 595.0;
    double pageHeight = 842.0;
    double marginLeft = 50.0;
    double marginRight = 50.0;
    double marginTop = 50.0;
    double marginBottom = 50.0;
    std::string fontName = "Helvetica";
    double titleFontSize = 18.0;
    double headerFontSize = 12.0;
    double bodyFontSize = 10.0;
    bool landscape = false;
};

struct SetlistPdfOptions : PdfPageOptions {
    std::string djName;
    std::string eventName;
    std::string venueName;
    std::string date;
    bool showBpmKey = true;
    bool showTimestamps = true;
    bool showEnergy = false;
    bool showGenre = false;
    bool showTrackNumbers = true;
    bool addLogo = false;
    std::string logoPath;
    std::string footerText = "Generated by BeatMate";
};

struct AnalysisReportOptions : PdfPageOptions {
    bool showWaveformPreview = false;
    bool showBpmGraph = true;
    bool showKeyDistribution = true;
    bool showEnergyGraph = true;
    bool showGenreBreakdown = true;
    bool showStatistics = true;
};

class PdfExportService {
public:
    PdfExportService() = default;
    ~PdfExportService() = default;

    bool exportSetlistPdf(const std::string& outputPath,
                           const std::vector<Models::Track>& tracks,
                           const std::vector<double>& startTimes,
                           const SetlistPdfOptions& options);

    bool exportAnalysisReport(const std::string& outputPath,
                                const std::vector<Models::Track>& tracks,
                                const AnalysisReportOptions& options);

    bool exportPlaylistPdf(const std::string& outputPath,
                             const Models::Playlist& playlist,
                             const std::vector<Models::Track>& tracks,
                             const PdfPageOptions& options = PdfPageOptions{});

    bool exportTrackCard(const std::string& outputPath,
                           const Models::Track& track,
                           const PdfPageOptions& options = PdfPageOptions{});

private:
    std::string generatePdfContent(const std::string& title,
                                     const std::vector<std::string>& lines,
                                     const PdfPageOptions& options) const;
    std::string formatTime(double seconds) const;
};

}
