#include "SetExportServiceComplete.h"
#include <spdlog/spdlog.h>
#include <nlohmann/json.hpp>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <cmath>

using json = nlohmann::json;

namespace BeatMate::Services::Export {

SetExportResult SetExportServiceComplete::exportSet(const std::string& outputDir,
                                                      const std::string& setName,
                                                      const std::vector<SetTrackEntry>& entries,
                                                      const SetExportOptions& options) {
    SetExportResult result;
    std::filesystem::create_directories(outputDir);
    std::string base = outputDir + "/" + setName;

    if (options.exportText) {
        result.textPath = base + ".txt";
        if (!exportAsText(result.textPath, entries, options))
            result.errors.push_back("Text export failed");
    }
    if (options.exportJson) {
        result.jsonPath = base + ".json";
        if (!exportAsJson(result.jsonPath, entries, options))
            result.errors.push_back("JSON export failed");
    }
    if (options.exportM3U) {
        result.m3uPath = base + ".m3u";
        if (!exportAsM3U(result.m3uPath, entries))
            result.errors.push_back("M3U export failed");
    }
    if (options.exportCue) {
        result.cuePath = base + ".cue";
        if (!exportAsCueSheet(result.cuePath, setName + ".wav", entries, options))
            result.errors.push_back("CUE export failed");
    }

    result.success = result.errors.empty();
    spdlog::info("SetExportServiceComplete: Exported set '{}' ({} tracks, {} errors)",
                 setName, entries.size(), result.errors.size());
    return result;
}

bool SetExportServiceComplete::exportAsText(const std::string& outputPath,
                                              const std::vector<SetTrackEntry>& entries,
                                              const SetExportOptions& options) {
    std::ofstream ofs(outputPath);
    if (!ofs.is_open()) return false;

    if (!options.djName.empty()) ofs << "DJ: " << options.djName << "\n";
    if (!options.eventName.empty()) ofs << "Event: " << options.eventName << "\n";
    if (!options.venueName.empty()) ofs << "Venue: " << options.venueName << "\n";
    if (!options.date.empty()) ofs << "Date: " << options.date << "\n";
    ofs << "Tracks: " << entries.size() << "\n";
    if (!entries.empty()) {
        double totalDuration = entries.back().endTime;
        ofs << "Total Duration: " << formatTime(totalDuration) << "\n";
    }
    ofs << std::string(60, '-') << "\n\n";

    for (const auto& e : entries) {
        ofs << std::setw(3) << e.position << ". ";
        if (options.includeTimestamps) {
            ofs << "[" << formatTime(e.startTime) << "] ";
        }
        ofs << e.artist << " - " << e.title;
        if (options.includeBpmKey) {
            ofs << " (" << std::fixed << std::setprecision(1) << e.bpm << " BPM";
            if (!e.key.empty()) ofs << ", " << e.key;
            ofs << ")";
        }
        ofs << "\n";
        if (options.includeTransitions && !e.transitionType.empty()) {
            ofs << "     -> " << e.transitionType;
            if (e.transitionLength > 0) ofs << " (" << std::setprecision(1) << e.transitionLength << "s)";
            ofs << "\n";
        }
    }

    if (!options.notes.empty()) {
        ofs << "\n" << std::string(60, '-') << "\nNotes: " << options.notes << "\n";
    }
    ofs << "\nGenerated by BeatMate\n";
    return true;
}

bool SetExportServiceComplete::exportAsJson(const std::string& outputPath,
                                              const std::vector<SetTrackEntry>& entries,
                                              const SetExportOptions& options) {
    json j;
    j["metadata"] = {
        {"djName", options.djName},
        {"eventName", options.eventName},
        {"venueName", options.venueName},
        {"date", options.date},
        {"notes", options.notes},
        {"trackCount", entries.size()},
        {"generator", "BeatMate"}
    };

    j["tracks"] = json::array();
    for (const auto& e : entries) {
        json track = {
            {"position", e.position},
            {"title", e.title},
            {"artist", e.artist},
            {"bpm", e.bpm},
            {"key", e.key},
            {"startTime", e.startTime},
            {"endTime", e.endTime},
            {"energy", e.energy}
        };
        if (!e.transitionType.empty()) {
            track["transition"] = {
                {"type", e.transitionType},
                {"length", e.transitionLength}
            };
        }
        j["tracks"].push_back(track);
    }

    std::ofstream ofs(outputPath);
    if (!ofs.is_open()) return false;
    ofs << j.dump(2);
    return true;
}

bool SetExportServiceComplete::exportAsM3U(const std::string& outputPath,
                                             const std::vector<SetTrackEntry>& entries) {
    std::ofstream ofs(outputPath);
    if (!ofs.is_open()) return false;

    ofs << "#EXTM3U\n";
    for (const auto& e : entries) {
        int duration = static_cast<int>(e.endTime - e.startTime);
        ofs << "#EXTINF:" << duration << "," << e.artist << " - " << e.title << "\n";
        ofs << e.filePath << "\n";
    }
    return true;
}

bool SetExportServiceComplete::exportAsCueSheet(const std::string& outputPath,
                                                  const std::string& audioFile,
                                                  const std::vector<SetTrackEntry>& entries,
                                                  const SetExportOptions& options) {
    std::ofstream ofs(outputPath);
    if (!ofs.is_open()) return false;

    if (!options.djName.empty()) ofs << "PERFORMER \"" << options.djName << "\"\n";
    if (!options.eventName.empty()) ofs << "TITLE \"" << options.eventName << "\"\n";
    ofs << "REM COMMENT \"Generated by BeatMate\"\n";
    ofs << "FILE \"" << audioFile << "\" WAVE\n";

    for (const auto& e : entries) {
        int trackNum = e.position;
        ofs << "  TRACK " << (trackNum < 10 ? "0" : "") << trackNum << " AUDIO\n";
        ofs << "    TITLE \"" << e.title << "\"\n";
        ofs << "    PERFORMER \"" << e.artist << "\"\n";

        int totalSec = static_cast<int>(e.startTime);
        int min = totalSec / 60;
        int sec = totalSec % 60;
        int frames = static_cast<int>((e.startTime - std::floor(e.startTime)) * 75.0);
        char timeBuf[16];
        std::snprintf(timeBuf, sizeof(timeBuf), "%02d:%02d:%02d", min, sec, frames);
        ofs << "    INDEX 01 " << timeBuf << "\n";
    }
    return true;
}

std::vector<SetTrackEntry> SetExportServiceComplete::buildFromTracks(
    const std::vector<Models::Track>& tracks,
    const std::vector<double>& startTimes) {

    std::vector<SetTrackEntry> entries;
    for (size_t i = 0; i < tracks.size(); ++i) {
        SetTrackEntry e;
        e.position = static_cast<int>(i + 1);
        e.title = tracks[i].title;
        e.artist = tracks[i].artist;
        e.bpm = tracks[i].bpm;
        e.key = tracks[i].key;
        e.energy = tracks[i].energy;
        e.filePath = tracks[i].filePath;
        e.startTime = (i < startTimes.size()) ? startTimes[i] : 0.0;
        e.endTime = e.startTime + tracks[i].duration;
        entries.push_back(e);
    }
    return entries;
}

std::string SetExportServiceComplete::formatTime(double seconds) const {
    int h = static_cast<int>(seconds) / 3600;
    int m = (static_cast<int>(seconds) % 3600) / 60;
    int s = static_cast<int>(seconds) % 60;
    char buf[16];
    if (h > 0) std::snprintf(buf, sizeof(buf), "%d:%02d:%02d", h, m, s);
    else std::snprintf(buf, sizeof(buf), "%02d:%02d", m, s);
    return buf;
}

}
